# Generated by Django 5.0.4 on 2026-01-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("user", "Normal User"),
                    ("agent", "Agent"),
                    ("company", "Company"),
                ],
                default="user",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_company",
            field=models.BooleanField(default=False),
        ),
    ]
