# Generated by Django 5.0.4 on 2026-01-19 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_account_type_user_is_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="can_post_properties",
            field=models.BooleanField(
                default=False, help_text="User can post properties after verification"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="id_number",
            field=models.CharField(
                blank=True,
                help_text="ID number used for verification",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="id_type",
            field=models.CharField(
                blank=True, help_text="nin, vnin, or bvn", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="id_verification_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="id_verified",
            field=models.BooleanField(
                default=False, help_text="User has verified their ID"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="API verification response data"
            ),
        ),
    ]
