# Generated by Django 5.0.4 on 2025-11-16 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('facebook_page', models.URLField(blank=True, null=True)),
                ('linkedin_page', models.URLField(blank=True, null=True)),
                ('instagram_page', models.URLField(blank=True, null=True)),
                ('x_page', models.URLField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('upline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downlines', to='agents.agent')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
