# Generated by Django 5.0.4 on 2026-01-09 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0004_company"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="can_post_properties",
            field=models.BooleanField(
                default=False,
                help_text="Agent can only post properties after verification",
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="id_card_back",
            field=models.ImageField(
                blank=True,
                help_text="Back of ID card (if applicable)",
                null=True,
                upload_to="agent_verification/id_cards/",
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="id_card_front",
            field=models.ImageField(
                blank=True,
                help_text="Front of ID card",
                null=True,
                upload_to="agent_verification/id_cards/",
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="id_number",
            field=models.CharField(
                blank=True,
                help_text="NIN, Passport, or Voter's Card number",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="id_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("nin", "National Identity Number (NIN)"),
                    ("passport", "International Passport"),
                    ("voters_card", "Voter's Card"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="id_verification_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="id_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="agent",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="selfie_photo",
            field=models.ImageField(
                blank=True,
                help_text="Selfie holding ID",
                null=True,
                upload_to="agent_verification/selfies/",
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="verification_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="API verification response data"
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Verification"),
                    ("in_review", "In Review"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_agents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="business_address_proof",
            field=models.FileField(
                blank=True,
                help_text="Additional address proof (Optional)",
                null=True,
                upload_to="company_verification/address/",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="cac_certificate",
            field=models.FileField(
                blank=True,
                help_text="CAC Certificate of Incorporation (Required)",
                null=True,
                upload_to="company_verification/cac/",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="cac_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="CAC verification response data"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="cac_verification_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="cac_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="company",
            name="can_post_properties",
            field=models.BooleanField(
                default=False,
                help_text="Company can only post properties after verification",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="directors_data",
            field=models.JSONField(
                blank=True, default=list, help_text="Directors information"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="directors_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="company",
            name="rc_number",
            field=models.CharField(
                blank=True, help_text="RC number from CAC", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="utility_bill",
            field=models.FileField(
                blank=True,
                help_text="Recent utility bill for address verification (Required)",
                null=True,
                upload_to="company_verification/utility_bills/",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="verification_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="company",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Verification"),
                    ("in_review", "In Review"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_companies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="VerificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verification_type",
                    models.CharField(
                        choices=[
                            ("nin", "NIN"),
                            ("passport", "Passport"),
                            ("voters_card", "Voter's Card"),
                            ("cac", "CAC"),
                            ("phone", "Phone"),
                            ("email", "Email"),
                            ("bank_account", "Bank Account"),
                            ("utility_bill", "Utility Bill"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "api_provider",
                    models.CharField(
                        blank=True, help_text="e.g., Dojah, VerifyMe", max_length=50
                    ),
                ),
                ("request_data", models.JSONField(blank=True, default=dict)),
                ("response_data", models.JSONField(blank=True, default=dict)),
                ("is_match", models.BooleanField(default=False)),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Admin notes", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Verification Log",
                "verbose_name_plural": "Verification Logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
