# Generated by Django 5.0.4 on 2026-01-19 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0005_agent_can_post_properties_agent_id_card_back_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="id_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("nin", "National Identity Number (NIN)"),
                    ("vnin", "Virtual NIN (vNIN)"),
                    ("bvn", "Bank Verification Number (BVN)"),
                    ("passport", "International Passport"),
                    ("voters_card", "Voter's Card"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="verificationlog",
            name="api_provider",
            field=models.CharField(
                blank=True, help_text="e.g., Kora, Persona, VerifyMe", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="verificationlog",
            name="verification_type",
            field=models.CharField(
                choices=[
                    ("nin", "NIN"),
                    ("vnin", "Virtual NIN"),
                    ("bvn", "BVN"),
                    ("passport", "Passport"),
                    ("voters_card", "Voter's Card"),
                    ("cac", "CAC"),
                    ("phone", "Phone"),
                    ("email", "Email"),
                    ("bank_account", "Bank Account"),
                    ("utility_bill", "Utility Bill"),
                ],
                max_length=20,
            ),
        ),
    ]
