# Generated by Django 5.0.4 on 2026-02-05 01:22

from django.db import migrations, models
from django.utils.text import slugify


def populate_agent_slugs(apps, schema_editor):
    """Populate slug field for all existing agents"""
    Agent = apps.get_model('agents', 'Agent')
    
    for agent in Agent.objects.all():
        if not agent.slug:
            # Generate slug from username
            base_slug = slugify(agent.user.username)
            slug = base_slug
            counter = 1
            
            # Ensure uniqueness
            while Agent.objects.filter(slug=slug).exclude(id=agent.id).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            
            agent.slug = slug
            agent.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0006_alter_agent_id_type_and_more"),
    ]

    operations = [
        # Step 1: Add slug field as nullable (no unique constraint yet)
        migrations.AddField(
            model_name="agent",
            name="slug",
            field=models.SlugField(
                blank=True,
                null=True,
                help_text="URL-friendly identifier",
                max_length=100,
            ),
        ),
        # Step 2: Populate slugs for existing agents
        migrations.RunPython(populate_agent_slugs, reverse_code=migrations.RunPython.noop),
        # Step 3: Now add the unique constraint
        migrations.AlterField(
            model_name="agent",
            name="slug",
            field=models.SlugField(
                blank=True,
                null=True,
                help_text="URL-friendly identifier",
                max_length=100,
                unique=True,
            ),
        ),
    ]
