# Generated by Django - add timestamp as needed

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_notification_savedproperty'),
    ]

    operations = [
        # Add new slot-based fields to UserSubscription
        migrations.AddField(
            model_name='usersubscription',
            name='total_slots',
            field=models.PositiveIntegerField(default=1, help_text='Total property posting slots owned (permanent)'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='used_slots',
            field=models.PositiveIntegerField(default=0, help_text='Number of slots currently in use'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='initial_free_slots',
            field=models.PositiveIntegerField(default=1, help_text='Free slots given initially (admin configurable)'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        # Add new slots_count field to ListingPackage
        migrations.AddField(
            model_name='listingpackage',
            name='slots_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of property posting slots in this package'),
            preserve_default=False,
        ),
        
        # Make old fields nullable for backward compatibility
        migrations.AlterField(
            model_name='listingpackage',
            name='listing_limit',
            field=models.PositiveIntegerField(blank=True, null=True, help_text='Deprecated: Use slots_count'),
        ),
        migrations.AlterField(
            model_name='listingpackage',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, null=True, help_text='Deprecated: Slots are permanent'),
        ),
        migrations.AlterField(
            model_name='listingpackage',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Deprecated'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='package',
            field=models.ForeignKey(blank=True, help_text='Last purchased package (for reference)', null=True, on_delete=models.deletion.SET_NULL, to='listings.listingpackage'),
        ),
    ]
