# Generated by Django 5.0.4 on 2025-12-31 09:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(default="Nestova", max_length=200),
                ),
                ("tagline", models.CharField(blank=True, max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "address_line1",
                    models.CharField(max_length=300, verbose_name="Address Line 1"),
                ),
                (
                    "address_line2",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Address Line 2"
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                ("country", models.CharField(default="United States", max_length=100)),
                ("phone", models.CharField(max_length=50, verbose_name="Phone Number")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email Address"),
                ),
                (
                    "support_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Support Email"
                    ),
                ),
                (
                    "weekday_hours",
                    models.CharField(default="9 AM - 6 PM", max_length=100),
                ),
                (
                    "weekend_hours",
                    models.CharField(default="9 AM - 4 PM", max_length=100),
                ),
                (
                    "google_maps_embed_url",
                    models.URLField(blank=True, verbose_name="Google Maps Embed URL"),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("facebook_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Contact Information",
                "verbose_name_plural": "Contact Information",
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Full Name")),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="Email Address",
                    ),
                ),
                ("subject", models.CharField(max_length=300, verbose_name="Subject")),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("read", "Read"),
                            ("replied", "Replied"),
                            ("archived", "Archived"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Submitted At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User Agent"),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, null=True, verbose_name="Admin Notes"),
                ),
                (
                    "replied_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Replied At"
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="contact_con_created_00b9df_idx"
                    ),
                    models.Index(
                        fields=["status"], name="contact_con_status_fa3e24_idx"
                    ),
                    models.Index(fields=["email"], name="contact_con_email_233940_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "subscribed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Subscribed At"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Active Subscription"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                (
                    "unsubscribed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Unsubscribed At"
                    ),
                ),
            ],
            options={
                "verbose_name": "Newsletter Subscription",
                "verbose_name_plural": "Newsletter Subscriptions",
                "ordering": ["-subscribed_at"],
                "indexes": [
                    models.Index(
                        fields=["-subscribed_at"], name="contact_new_subscri_feceff_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="contact_new_is_acti_0530d3_idx"
                    ),
                ],
            },
        ),
    ]
