# Generated by Django 5.0.4 on 2026-01-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactinfo",
            name="google_maps_embed_url",
            field=models.URLField(
                blank=True, max_length=1000, verbose_name="Google Maps Embed URL"
            ),
        ),
    ]
