# Generated by Django 5.0.4 on 2026-02-05 14:08

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InteriorDesignRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("residential", "Residential Design"),
                            ("commercial", "Commercial Design"),
                            ("renovation", "Renovation & Remodeling"),
                            ("consultation", "Design Consultation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "property_address",
                    models.TextField(
                        help_text="Full address of the property to be designed"
                    ),
                ),
                (
                    "property_size",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 2000 sq ft, 3 bedroom apartment",
                        max_length=100,
                    ),
                ),
                (
                    "budget_range",
                    models.CharField(
                        choices=[
                            ("0-500000", "Under ₦500,000"),
                            ("500000-1000000", "₦500,000 - ₦1,000,000"),
                            ("1000000-3000000", "₦1,000,000 - ₦3,000,000"),
                            ("3000000-5000000", "₦3,000,000 - ₦5,000,000"),
                            ("5000000+", "Above ₦5,000,000"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "preferred_style",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Modern, Contemporary, Traditional, Minimalist",
                        max_length=200,
                    ),
                ),
                (
                    "project_description",
                    models.TextField(
                        help_text="Describe your vision and requirements for the project"
                    ),
                ),
                ("preferred_start_date", models.DateField(blank=True, null=True)),
                ("project_deadline", models.DateField(blank=True, null=True)),
                (
                    "reference_images",
                    models.FileField(
                        blank=True,
                        help_text="Upload inspiration images (optional)",
                        null=True,
                        upload_to="interior_design/references/",
                    ),
                ),
                (
                    "special_requirements",
                    models.TextField(
                        blank=True,
                        help_text="Any special requirements or considerations",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("contacted", "Client Contacted"),
                            ("in_progress", "Project In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, help_text="Internal notes for admin/designers"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("contacted_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interior_design_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Interior Design Request",
                "verbose_name_plural": "Interior Design Requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
