# Generated by Django 5.0.4 on 2026-01-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "category", "verbose_name_plural": "categories"},
        ),
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("Published", "PUBLISHED"), ("draft", "DRAFT")],
                default="draft",
                max_length=100,
            ),
        ),
    ]
