# Generated by Django 5.0.4 on 2026-01-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0003_alter_author_user_alter_post_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=256, unique_for_date="publish"),
        ),
    ]
