# Generated by Django 5.0.4 on 2025-12-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paystack_access_code",
            field=models.CharField(
                blank=True, help_text="Paystack access code", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="paystack_reference",
            field=models.CharField(
                blank=True, help_text="Paystack transaction reference", max_length=200
            ),
        ),
    ]
