# Generated by Django 5.0.4 on 2025-12-30 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0003_propertysale_commission"),
        ("shop", "0002_order_paystack_access_code_order_paystack_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="referred_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referred_customers",
                to="agents.agent",
            ),
        ),
    ]
