# Generated by Django 5.0.4 on 2025-12-10 23:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_apartment_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
