# Generated by Django 5.0.4 on 2025-12-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_apartment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
