# Generated by Django 5.0.4 on 2026-01-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_apartment_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apartment",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
