# Generated by Django 5.0.4 on 2025-11-20 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(default='bi bi-check-circle', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Property Amenities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('for_sale', 'For Sale'), ('for_rent', 'For Rent'), ('sold', 'Sold'), ('rented', 'Rented'), ('pending', 'Pending')], max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Property Statuses',
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('condo', 'Condo'), ('townhouse', 'Townhouse'), ('land', 'Land'), ('commercial', 'Commercial'), ('duplex', 'Duplex'), ('bungalow', 'Bungalow'), ('mansion', 'Mansion'), ('villa', 'Villa')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='bi bi-house-door', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=500)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('bedrooms', models.PositiveIntegerField(default=0)),
                ('bathrooms', models.PositiveIntegerField(default=0)),
                ('square_feet', models.PositiveIntegerField(help_text='Property size in square feet')),
                ('lot_size', models.PositiveIntegerField(blank=True, help_text='Lot size in square feet', null=True)),
                ('year_built', models.PositiveIntegerField(blank=True, null=True)),
                ('parking_spaces', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('price_per_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('has_garage', models.BooleanField(default=False)),
                ('has_pool', models.BooleanField(default=False)),
                ('has_garden', models.BooleanField(default=False)),
                ('has_security', models.BooleanField(default=False)),
                ('has_gym', models.BooleanField(default=False)),
                ('has_balcony', models.BooleanField(default=False)),
                ('is_furnished', models.BooleanField(default=False)),
                ('has_ac', models.BooleanField(default=False)),
                ('has_heating', models.BooleanField(default=False)),
                ('pet_friendly', models.BooleanField(default=False)),
                ('additional_features', models.JSONField(blank=True, help_text='Store additional features as JSON', null=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='properties/featured/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo URL')),
                ('virtual_tour_url', models.URLField(blank=True, help_text='360° virtual tour URL')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_hot', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('is_exclusive', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('saved_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listed_date', models.DateField(auto_now_add=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True, max_length=500)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='property.city')),
                ('listed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listed_properties', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='property.propertystatus')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='property.propertytype')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='property.state')),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='property.property')),
            ],
            options={
                'ordering': ['order', '-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='property.state'),
        ),
        migrations.CreateModel(
            name='PropertyAmenityLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.propertyamenity')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_amenities', to='property.property')),
            ],
            options={
                'unique_together': {('property', 'amenity')},
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['state', 'city'], name='property_pr_state_i_bcef32_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type'], name='property_pr_propert_91c9e3_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['price'], name='property_pr_price_b1d594_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['-created_at'], name='property_pr_created_82f744_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'state')},
        ),
    ]
