# Generated by Django 5.0.4 on 2025-11-22 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertytype',
            options={'ordering': ['category', 'display_order', 'name']},
        ),
        migrations.AddField(
            model_name='propertytype',
            name='category',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('land', 'Land'), ('special', 'Special')], default='residential', max_length=20),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='name',
            field=models.CharField(choices=[('detached_house', 'Detached House'), ('semi_detached', 'Semi-Detached House'), ('terrace', 'Terrace/Townhouse'), ('duplex', 'Duplex'), ('bungalow', 'Bungalow'), ('mansion', 'Mansion'), ('villa', 'Villa'), ('cottage', 'Cottage'), ('studio', 'Studio Apartment'), ('1_bed_flat', '1-Bedroom Flat'), ('2_bed_flat', '2-Bedroom Flat'), ('3_bed_flat', '3-Bedroom Flat'), ('4_bed_flat', '4+ Bedroom Flat'), ('penthouse', 'Penthouse'), ('maisonette', 'Maisonette'), ('serviced_apt', 'Serviced Apartment'), ('self_contain', 'Self-Contain'), ('room_parlour', 'Room and Parlour'), ('mini_flat', 'Mini Flat'), ('boys_quarters', 'Boys Quarters (BQ)'), ('office', 'Office Space'), ('shop', 'Shop/Store'), ('mall', 'Shopping Mall'), ('showroom', 'Showroom'), ('warehouse', 'Warehouse'), ('factory', 'Factory'), ('hotel', 'Hotel'), ('event_center', 'Event Center'), ('filling_station', 'Filling Station'), ('residential_land', 'Residential Land'), ('commercial_land', 'Commercial Land'), ('agricultural_land', 'Agricultural Land'), ('industrial_land', 'Industrial Land'), ('mixed_use_land', 'Mixed-Use Land'), ('compound', 'Compound'), ('estate_house', 'Estate House'), ('farm_house', 'Farm House'), ('student_accommodation', 'Student Accommodation')], max_length=50, unique=True),
        ),
    ]
