# Generated by Django 5.0.4 on 2025-11-22 00:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_propertytype_options_propertytype_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
