# Generated by Django 5.0.4 on 2025-12-30 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0003_propertysale_commission"),
        ("property", "0003_alter_property_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="referring_agent",
            field=models.ForeignKey(
                blank=True,
                help_text="Agent who referred the buyer",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referred_properties",
                to="agents.agent",
            ),
        ),
    ]
