# Generated by Django 5.0.4 on 2026-01-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0004_property_referring_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
