# Generated by Django 5.0.4 on 2026-01-29 02:18

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0005_property_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="video_url",
            field=embed_video.fields.EmbedVideoField(
                blank=True, help_text="YouTube or Vimeo URL"
            ),
        ),
    ]
