# Generated by Django 5.0.4 on 2026-01-29 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0006_alter_agent_id_type_and_more"),
        ("property", "0006_alter_property_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="properties",
                to="agents.agent",
            ),
        ),
    ]
