# Generated by Django 5.0.4 on 2026-02-27 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0008_alter_property_listed_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("reviewing", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("mr", "Mr"),
                            ("mrs", "Mrs"),
                            ("miss", "Miss"),
                            ("ms", "Ms"),
                            ("dr", "Dr"),
                            ("prof", "Prof"),
                            ("engr", "Engr"),
                            ("chief", "Chief"),
                            ("alhaji", "Alhaji"),
                            ("alhaja", "Alhaja"),
                            ("barr", "Barr"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("surname", models.CharField(max_length=100)),
                ("firstname", models.CharField(max_length=100)),
                ("other_names", models.CharField(blank=True, max_length=100)),
                ("residential_address", models.TextField()),
                ("phone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("date_of_birth", models.DateField()),
                ("nationality", models.CharField(default="Nigerian", max_length=100)),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("single", "Single"),
                            ("married", "Married"),
                            ("divorced", "Divorced"),
                            ("widowed", "Widowed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("occupation", models.CharField(max_length=150)),
                ("place_of_work", models.CharField(blank=True, max_length=200)),
                ("work_address", models.TextField(blank=True)),
                (
                    "passport_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="applications/passports/"
                    ),
                ),
                (
                    "id_type",
                    models.CharField(
                        choices=[
                            ("national_id", "National Identity Card"),
                            ("drivers_licence", "Driver's Licence / Permit"),
                            ("intl_passport", "International Passport"),
                            ("voters_card", "Voter's Card"),
                        ],
                        max_length=20,
                    ),
                ),
                ("id_number", models.CharField(max_length=100)),
                (
                    "id_document",
                    models.FileField(
                        blank=True,
                        help_text="Scanned copy / photo of the ID document",
                        null=True,
                        upload_to="applications/ids/",
                    ),
                ),
                (
                    "is_pep",
                    models.BooleanField(
                        default=False,
                        verbose_name="Are you (or related to) a Politically Exposed Person (PEP)?",
                    ),
                ),
                (
                    "pep_details",
                    models.CharField(
                        blank=True,
                        help_text="Name and position held (required if PEP is Yes)",
                        max_length=300,
                    ),
                ),
                (
                    "nok_name",
                    models.CharField(
                        max_length=200, verbose_name="Name of Next of Kin"
                    ),
                ),
                (
                    "nok_relationship",
                    models.CharField(
                        choices=[
                            ("spouse", "Spouse"),
                            ("parent", "Parent"),
                            ("sibling", "Sibling"),
                            ("child", "Child"),
                            ("friend", "Friend"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Relationship",
                    ),
                ),
                (
                    "nok_phone",
                    models.CharField(
                        max_length=20, verbose_name="Next of Kin Phone Number"
                    ),
                ),
                (
                    "nok_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Next of Kin Email"
                    ),
                ),
                ("nok_address", models.TextField(verbose_name="Next of Kin Address")),
                (
                    "floor_choice",
                    models.CharField(
                        choices=[
                            ("ground", "Ground Floor"),
                            ("first", "First Floor"),
                            ("second", "Second Floor"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "number_of_shops",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Number of Shop Units"
                    ),
                ),
                (
                    "payment_plan",
                    models.CharField(
                        choices=[
                            ("3_month", "3-Month Plan"),
                            ("6_month", "6-Month Plan"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "intended_use",
                    models.TextField(
                        help_text="e.g. retail, office, service centre, etc.",
                        verbose_name="Intended Use of the Shopping Unit",
                    ),
                ),
                (
                    "aml_accepted",
                    models.BooleanField(
                        default=False, verbose_name="AML/CFT Declaration Accepted"
                    ),
                ),
                (
                    "subscriber_signature",
                    models.ImageField(
                        blank=True,
                        help_text="Upload a scanned signature image",
                        null=True,
                        upload_to="applications/signatures/",
                    ),
                ),
                ("realtor_name", models.CharField(blank=True, max_length=200)),
                ("realtor_email", models.EmailField(blank=True, max_length=254)),
                ("realtor_phone", models.CharField(blank=True, max_length=20)),
                (
                    "realtor_cid",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Realtor CID Number"
                    ),
                ),
                (
                    "applicant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="property_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="property.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Application",
                "verbose_name_plural": "Property Applications",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
