# Generated by Django 5.0.4 on 2026-02-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0009_propertyapplication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyapplication",
            name="floor_choice",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ground", "Ground Floor"),
                    ("first", "First Floor"),
                    ("second", "Second Floor"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="propertyapplication",
            name="intended_use",
            field=models.TextField(
                blank=True,
                help_text="e.g. retail, office, service centre, etc.",
                null=True,
                verbose_name="Intended Use of the Shopping Unit",
            ),
        ),
        migrations.AlterField(
            model_name="propertyapplication",
            name="number_of_shops",
            field=models.PositiveIntegerField(
                blank=True, default=1, null=True, verbose_name="Number of Shop Units"
            ),
        ),
        migrations.AlterField(
            model_name="propertyapplication",
            name="payment_plan",
            field=models.CharField(
                blank=True,
                choices=[("3_month", "3-Month Plan"), ("6_month", "6-Month Plan")],
                max_length=10,
                null=True,
            ),
        ),
    ]
